In [2]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.datasets import load_iris

In [7]:
iris=load_iris()

In [40]:
df=pd.DataFrame(iris.data)

In [45]:
df.columns=iris.feature_names

In [46]:
df['species']=iris.target

In [47]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [48]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [51]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [57]:
x=df.drop(['species'],axis=1)
y=df['species']

In [59]:
from sklearn.model_selection import train_test_split

In [61]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=10)

In [63]:
from sklearn.neighbors import KNeighborsClassifier

In [65]:
model=KNeighborsClassifier()

In [68]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [70]:
model.score(x_train,y_train)

0.9777777777777777

In [72]:
train_pred=model.predict(x_train)

In [74]:
test_pred=model.predict(x_test)

In [76]:
from sklearn.metrics import confusion_matrix

In [78]:
confusion_matrix(y_train,train_pred)

array([[45,  0,  0],
       [ 0, 40,  2],
       [ 0,  1, 47]], dtype=int64)

In [80]:
model.score(x_test,test_pred)

1.0

In [82]:
confusion_matrix(y_test,test_pred)

array([[5, 0, 0],
       [0, 7, 1],
       [0, 0, 2]], dtype=int64)

In [99]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
145        2  
146        2  
147        2  
148        2  
149        2

In [100]:
model.predict([[6.2,1.4,4.3,1.9]])

D:\applications\anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([2])